# src/main/resources/application-prod.properties
# This profile is activated for production deployments
# Spring Application Name
spring.application.name=relatives

# Spring DataSource Configuration
spring.datasource.url=${MYSQL_CONNECTION}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring JPA Configuration
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.alpacaflow.meditrack.relatives.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7